name: Ejecutar Notebooks

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar Jupyter y dependencias del proyecto
        run: |
          pip install -r requirements.txt
          pip install notebook nbconvert

      - name: Ejecutar notebooks
        run: |
          jupyter nbconvert --to notebook --execute CDR_Presentacion-01.ipynb --output ejecutado-01.ipynb
          jupyter nbconvert --to notebook --execute CDR_Presentacion-02.ipynb --output ejecutado-02.ipynb
